### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by JalilArfaoui**
Hi @orzilca 

Thanks for this module, it's really useful for my tests. 

I had some difficulties making it work, and then understanding clearly the code, so I ended up with this big refacto. 

Would you like to consider reviewing or/and merging ?

What is new or different : 

- Callback is called with a wrapping object instead of multiple arguments, which I find more future proof.
- Resulting object also contains raw responseData
- Resulting object does not JSON.parse requestData, in case not JSON. 
- Callback is not called anymore if not request could be catched. Instead, a failed assertion is emitted. 
- Polling is done by rescheduling instead of setInterval to avoid polling collision
- Added a very simple but useful `isXHRSuccess` assertion. 
- Fragmented into multiple files to increase readability and maintenance
- Parts rewritten using ES6 (I find it more readable)
- Transpile script so that ES5 lib is still available
- Tests
- Updated readme accordingly

What do you think ?

### CODE REVIEW

**Comment by orzilca** [comment]
@JalilArfaoui those are some great changes and updates!

I will go over them and will merge asap.

thanks!

**Comment by JalilArfaoui** [comment]
Great @orzilca, happy to help

Please keep in mind that this will be a breaking release, for mainly because of the argument change in the callback.

**Comment by orzilca** [comment]
Hey @JalilArfaoui 
Sorry for the delay, busy days..

I will get to it shortly!

**Comment by JalilArfaoui** [comment]
Hi @orzilca 
Did you have a chance to take a look ? 
I just pushed some significant changes : I've taken a step forward because I needed to listen to multiple simultaneous requests in one of my project. 
So there is now 2 separated commands : 
`waitForXHR`  => `callback` is only called at the end of the given `delay`, with an array of all listened requests matching `urlPattern`. 
`waitForFirstXHR` => old behavior : Calls `callback` as soon as a matching requests as been completed.  
Also I added Flow Type. 
Hope you like it !

**Comment by orzilca** [comment]
@JalilArfaoui 

Everything looks good except for the webstorm setting, I dont think those should be included in the project.
This is just a package within a project, and should be stay opinionated to any editor.

If you can revert the last commit (e146fd0a13a990c4549901aa8aca2ef8ca5b29cd) I will merge the pull request.

**Comment by JalilArfaoui** [comment]
Hi @orzilca 
I figured it would't hurt and could be usefull to anyone using the same editor. 
I removed the commit and updated the `.gitignore` accordingly. 
Ready to merge :-)

**Comment by orzilca** [comment]
thanks @JalilArfaoui 
merged!

**Comment by JalilArfaoui** [comment]
Fantastic @orzilca 
Do you have a plan to bump 0.3 version and publish to npm soon ?

**Comment by orzilca** [comment]
Done @JalilArfaoui

**Pull request merged**
