### PR TITLE
updated profile url to GitHub profile

### PR DESCRIPTION
**Pull request by orzilca**

### CODE REVIEW

**Comment by JalilArfaoui** [comment]
@orzilca  You have to `yarn contributors:generate` to update the `README.md`

**Comment by JalilArfaoui** [comment]
By the way, do you any information about Sergey Titievsky and Veetil ?

**Comment by orzilca** [comment]
I have sergey's profile, I'll update

**Comment by orzilca** [comment]
@JalilArfaoui the yarn command is not working properly..

```bash
yarn contributors:generate
yarn run v1.3.2
$ all-contributors generate
/bin/sh: all-contributors: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by orzilca** [comment]
anyhow, this is Sergey's profile: https://github.com/cseregat

**Comment by JalilArfaoui** [comment]
Did you run `yarn` after pull the repo to install new module ?

**Comment by JalilArfaoui** [comment]
I can do it if you prefer ... ?

**Comment by orzilca** [comment]
already updated it, no worries!

**Comment by JalilArfaoui** [comment]
👍🏼

**Pull request merged**
